server:
  port: 7001

spring:
  application:
    name: cloud2020-eureka-server

eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示不从注册中心抓取服务信息
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka