server:
  port: 8002

spring:
  application:
    name: cloud2020-provide-user
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:8068/clouddb2020_2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      password: QAZ123wsx++
      username: root
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    prefer-ip-address: true
    instance-id: cloud2020-provider-user-8002