server:
  port: 9001
spring:
  application:
    name: cloudalibaba-provider-nacos-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 84a87126-fcb8-47bb-b72f-8ea8dc2d1dba
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:8068/clouddb2020_1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      password: QAZ123wsx++
      username: root
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
management:
  endpoints:
    web:
      exposure:
        include: "*"